@echo off
setlocal EnableExtensions

REM ======================================================
REM Clean build artifacts generated by PyInstaller
REM IMPORTANT:
REM - Do NOT delete *.spec because the build script depends on it.
REM - Only remove build/ dist/ and caches/logs.
REM ======================================================

echo Cleaning build artifacts...

REM PyInstaller output
if exist build (
  echo - Removing build\
  rmdir /s /q build
)
if exist dist (
  echo - Removing dist\
  rmdir /s /q dist
)

REM Python caches
if exist __pycache__ (
  echo - Removing __pycache__\
  rmdir /s /q __pycache__
)
for /d /r %%D in (__pycache__) do (
  if exist "%%D" (
    echo - Removing %%D
    rmdir /s /q "%%D"
  )
)

REM Log files (optional)
for %%F in (*.log) do (
  echo - Deleting %%F
  del /f /q "%%F"
)
if exist logs (
  echo - Removing logs\
  rmdir /s /q logs
)

echo.
echo Done.
pause
