@echo off
setlocal EnableExtensions

REM ======================================================
REM Clean all build artifacts generated by build_exe.bat
REM Keeps only your source code files.
REM ======================================================

echo Cleaning build artifacts...

REM PyInstaller output
if exist build (
  echo - Removing build\
  rmdir /s /q build
)
if exist dist (
  echo - Removing dist\
  rmdir /s /q dist
)

REM PyInstaller spec file(s)
for %%F in (*.spec) do (
  echo - Deleting %%F
  del /f /q "%%F"
)

REM Python caches
if exist __pycache__ (
  echo - Removing __pycache__\
  rmdir /s /q __pycache__
)
for /d /r %%D in (__pycache__) do (
  if exist "%%D" (
    echo - Removing %%D
    rmdir /s /q "%%D"
  )
)

REM Virtual environment (optional). Uncomment if you want to remove it too.
REM if exist .venv (
REM   echo - Removing .venv\
REM   rmdir /s /q .venv
REM )

REM Log files (optional)
for %%F in (*.log) do (
  echo - Deleting %%F
  del /f /q "%%F"
)
if exist logs (
  echo - Removing logs\
  rmdir /s /q logs
)

echo.
echo Done. Only source files remain.
pause

